all:
  children:
    vps:
      hosts:
        mc-vps:
          ansible_host: 89.167.98.246
          ansible_user: root
    macbook:
      hosts:
        localhost:
          ansible_connection: local
